name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - run: sudo apt-get install uuid-dev nasm
      - run: |
          make
          mkdir -p output
          cp CloverPackage/CloverV2/BootSectors/boot0ss CloverPackage/CloverV2/BootSectors/boot1f32 Build/Clover/RELEASE_GCC131/FV/boot output/
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Clover-Duet
          path: |
            output/*
